### ISSUE TITLE
无法在Xcode 12+上安装

### ISSUE THREAD

**Issue by Fater7** [Dtheme/Xcode-AutoLazyLoad#1]
按照操作顺序操作后，Editor中没有Lazyload

**Comment by fengyunjue** [comment]
你好，请问你是安装成功了吗，我按照步骤在xcode12上编译工程并运行了AutoLazyLoad.app，在系统的偏好设置里没有找到AutoLazyLoad，能请教下你是怎么做的吗？

**Comment by Dtheme** [comment]
最近太忙，另外我还没来得及升级，还没时间看，你可以自己先尝试一下。应该是其他人关掉的。如果解决我会及时回复。谢谢。





------------------ 原始邮件 ------------------
发件人: fengyunjue <notifications@github.com&gt;
发送时间: 2020年12月2日 20:19
收件人: Dtheme/Xcode-AutoLazyLoad <Xcode-AutoLazyLoad@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Dtheme/Xcode-AutoLazyLoad] 无法在Xcode 12+上安装 (#1)





 
你好，请问你是安装成功了吗，我按照步骤在xcode12上编译工程并运行了AutoLazyLoad.app，在系统的偏好设置里没有找到AutoLazyLoad，能请教下你是怎么做的吗？

**Comment by fengyunjue** [comment]
我已经安装上去了，xcode版本12.1，我出现的问题是在系统偏好设置->扩展里，没有找到xcode Source Editor，在网上查找的原因是存在两个xcode的原因，解决方法：在应用程序中，将正在使用的xcode先修改下名字（如：xcode1），然后在修改回来，扩展里就会显示xcode Source Editor了，之后就按文档的步骤就成功了，感谢你的回复
